git submodule add -b 14.0 git@github.com:OCA/account-analytic.git oca/account-analytic
git submodule add -b 14.0 git@github.com:OCA/account-budgeting.git oca/account-budgeting
git submodule add -b 14.0 git@github.com:OCA/account-closing.git oca/account-closing
git submodule add -b 14.0 git@github.com:OCA/account-financial-reporting.git oca/account-financial-reporting
git submodule add -b 14.0 git@github.com:OCA/account-financial-tools.git oca/account-financial-tools
git submodule add -b 14.0 git@github.com:OCA/account-invoice-reporting.git oca/account-invoice-reporting
git submodule add -b 14.0 git@github.com:OCA/account-invoicing.git oca/account-invoicing
git submodule add -b 14.0 git@github.com:OCA/account-payment.git oca/account-payment
git submodule add -b 14.0 git@github.com:OCA/account-reconcile.git oca/account-reconcile
git submodule add -b 14.0 git@github.com:OCA/bank-payment.git oca/bank-payment
git submodule add -b 14.0 git@github.com:OCA/brand.git oca/brand
git submodule add -b 14.0 git@github.com:OCA/commission.git oca/commission
git submodule add -b 14.0 git@github.com:OCA/community-data-files.git oca/community-data-files
git submodule add -b 14.0 git@github.com:OCA/connector.git oca/connector
git submodule add -b 14.0 git@github.com:OCA/contract.git oca/contract
git submodule add -b 14.0 git@github.com:OCA/crm.git oca/crm
git submodule add -b 14.0 git@github.com:OCA/currency.git oca/currency
git submodule add -b 14.0 git@github.com:OCA/delivery-carrier.git oca/delivery-carrier
git submodule add -b 14.0 git@github.com:OCA/field-service.git oca/field-service
git submodule add -b 14.0 git@github.com:OCA/geospatial.git oca/geospatial
git submodule add -b 14.0 git@github.com:OCA/helpdesk.git oca/helpdesk
git submodule add -b 14.0 git@github.com:OCA/hr.git oca/hr
git submodule add -b 14.0 git@github.com:OCA/knowledge.git oca/knowledge
git submodule add -b 14.0 git@github.com:OCA/l10n-brazil.git custom/l10n-brazil
git submodule add -b 14.0 git@github.com:OCA/management-system.git oca/management-system
git submodule add -b 14.0 git@github.com:OCA/manufacture.git oca/manufacture
git submodule add -b 14.0 git@github.com:OCA/mis-builder.git oca/mis-builder
git submodule add -b 14.0 git@github.com:OCA/partner-contact.git oca/partner-contact
git submodule add -b 14.0 git@github.com:OCA/pos.git oca/pos
git submodule add -b 14.0 git@github.com:OCA/product-attribute.git oca/product-attribute
git submodule add -b 14.0 git@github.com:OCA/project.git oca/project
git submodule add -b 14.0 git@github.com:OCA/project-reporting.git oca/project-reporting
git submodule add -b 14.0 git@github.com:OCA/purchase-workflow.git oca/purchase-workflow
git submodule add -b 14.0 git@github.com:OCA/queue.git oca/queue
git submodule add -b 14.0 git@github.com:OCA/reporting-engine.git oca/reporting-engine
git submodule add -b 14.0 git@github.com:OCA/sale-reporting.git oca/sale-reporting
git submodule add -b 14.0 git@github.com:OCA/sale-workflow.git oca/sale-workflow
git submodule add -b 14.0 git@github.com:OCA/server-backend.git oca/server-backend
git submodule add -b 14.0 git@github.com:OCA/server-env.git oca/server-env
git submodule add -b 14.0 git@github.com:OCA/server-tools.git oca/server-tools
git submodule add -b 14.0 git@github.com:OCA/server-ux.git oca/server-ux
git submodule add -b 14.0 git@github.com:OCA/stock-logistics-barcode.git oca/stock-logistics-barcode
git submodule add -b 14.0 git@github.com:OCA/stock-logistics-warehouse.git oca/stock-logistics-warehouse
git submodule add -b 14.0 git@github.com:OCA/stock-logistics-workflow.git oca/stock-logistics-workflow
git submodule add -b 14.0 git@github.com:OCA/storage.git oca/storage
git submodule add -b 14.0 git@github.com:OCA/timesheet.git oca/timesheet
git submodule add -b 14.0 git@github.com:OCA/web.git oca/web
git submodule add -b 14.0 git@github.com:OCA/website.git oca/website
